Módulo VI - Back-end: Criando API com Node.Js

Instalando e Configurando seu Ambiente Node.js

Introdução ao Node.js com JavaScript

Fundamentos de Node.js e Jest

Pirâmide de Testes na Prática Explorando Jest e TDD

Aplicando o Estilo Arquitetural REST com Node.js

Node.js com Bancos de Dados Relacionais (SQL)

Microsserviços e Integrações com Node.js

Criando uma API REST com Node.js e TypeORM

Desafio de projeto
Integrando um Baackend em Node.js com um Frontend em React para um Ecommerce 
